version: '3.9'
services:
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: ${COMPOSER_PROJECT_NAME}-nginx
        restart: unless-stopped
        tty: true
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ../:/var/project
        networks:
            - mesgen

    php-fpm:
        build:
            context: ./php
            dockerfile: Dockerfile
        container_name: ${COMPOSER_PROJECT_NAME}-php
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:host-gateway"       # for Xdebug
        tty: true
        environment:
            PHP_IDE_CONFIG: "serverName=job-php-fpm"    # for Xdebug
        expose:
            - 9000
        volumes:
            - ../:/var/project
            # - ./php/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
            # - ./php/xdebug/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini:ro
            # - ./php/xdebug/logs/xdebug.log:/tmp/xdebug.log
        networks:
            - mesgen

    postgres:
        image: postgres:12
        container_name: ${COMPOSER_PROJECT_NAME}-postgres
        restart: unless-stopped
        volumes:
            - ./postgres/data/:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: devsecret
            POSTGRES_USER: devuser
            POSTGRES_DB: devdb
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - ${POSTGRES_PORT}:5432
        networks:
            - mesgen

    redoc:
        image: redocly/redoc
        container_name: ${COMPOSER_PROJECT_NAME}-redoc
        restart: unless-stopped
        tty: true
        volumes:
            - ../docs/:/usr/share/nginx/html/swagger/
        environment:
            - SPEC_URL=swagger/api-docs.yml
        ports:
            - 5555:80
            - 5556:8080
        networks:
            - mesgen

networks:
    mesgen:
        driver: bridge
